fix poi icons, dialog
osmandapp/web pull request #140
Opened 2023-07-19 08:35 UTC by alisa911

2023-07-19 08:35 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/1903

2023-07-20 13:32 UTC, RZR-UA requested changes

2023-07-20 13:32 UTC, RZR-UA commented on map/src/context/PoiManager.js
> +            type = poiFilters[`${type}`].length > 1 ? poiFilters[`${type}`][1] : poiFilters[`${type}`][0];
use **type** instead of ${type}

2023-07-20 13:32 UTC, RZR-UA commented on map/src/context/PoiManager.js
> +    if (type) {
Why not if (type && rename)?

2023-07-20 13:32 UTC, RZR-UA commented on map/src/drawer/components/poi/PoiTypesDialog.jsx
> +        filters = filters.filter((f) => f !== 'routes');
Do you really need to modify function parameter and then return it also? If not, just use **return filters.filter(...)**

2023-07-20 13:32 UTC, RZR-UA commented on map/src/drawer/components/poi/PoiTypesDialog.jsx
> +                    {removeUnusedFilters(ctx.poiCategory?.filters).map((item, key) => (
Need key for Grid (as 1st element under map-cycle)

2023-07-20 16:33 UTC, RZR-UA approved these changes

2023-07-20 16:34 UTC, merged