Web - rename menu items
osmandapp/web pull request #227
Opened 2023-09-18 10:18 UTC by alisa911

2023-09-18 10:19 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2208

2023-09-19 07:17 UTC, RZR-UA approved these changes

2023-09-19 07:18 UTC, RZR-UA requested changes

2023-09-19 07:18 UTC, RZR-UA commented on map/src/drawer/components/PlanRouteMenu.jsx
> +                                id="se-upload-gpx"
Please change id (both lines) to "planroute-upload-gpx"

2023-09-19 07:54 UTC, merged