Fix  road attributes
osmandapp/web pull request #237
Opened 2023-09-22 14:33 UTC by alisa911

2023-09-22 14:33 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2088

2023-09-25 10:20 UTC, alisa911 commented
<img width="400" alt="Screenshot 2023-09-25 at 13 19 40" src="https://github.com/osmandapp/web/assets/38911173/832ded47-7c11-4dee-9088-43e2dc644695">
<img width="407" alt="Screenshot 2023-09-25 at 13 19 48" src="https://github.com/osmandapp/web/assets/38911173/daea350e-1a7f-4c70-bf28-21c847bf7b8b">
<img width="400" alt="Screenshot 2023-09-25 at 13 20 05" src="https://github.com/osmandapp/web/assets/38911173/5e36ae9f-d5d1-4c6d-8362-208183a03142">

2023-09-25 10:47 UTC, RZR-UA commented on map/src/infoblock/components/graph/GpxGraph.jsx
> +                max: Number(data[data.length - 1][xAxis].toFixed(1)),
Did you mean:

max: Number(data[data.length - 1][xAxis]).toFixed(1),

?

2023-09-25 10:47 UTC, RZR-UA commented on map/src/infoblock/components/graph/RoadAttributesGraph.jsx
> +            }
value.distance < 0.01 (_in meters?_) = '< 10m' ?

Possibly better to use value.distance < 10

2023-09-25 10:47 UTC, RZR-UA commented on map/src/infoblock/components/graph/RoadAttributesGraph.jsx
> +                    onMouseLeave={() => hideSelectedPointSegment()}
onMouseLeave={hideSelectedPointSegment}

No need to create new function () => xxx() every time when you not use arguments such as: (e) => xxx(e)

2023-09-26 13:01 UTC, RZR-UA approved these changes

2023-09-27 08:35 UTC, RZR-UA requested changes

2023-09-27 08:35 UTC, RZR-UA commented on map/src/infoblock/components/graph/RoadAttributesGraph.jsx
> +            if (activeIndex) {
Double if ?

2023-09-27 08:49 UTC, RZR-UA approved these changes

2023-09-27 08:49 UTC, merged