Tracks redesign
osmandapp/web pull request #270
Opened 2023-10-30 15:36 UTC by alisa911

2023-10-30 15:36 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2204

2023-11-02 18:58 UTC, RZR-UA requested changes

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/CloudTrackItem.jsx
> +
Better to use empty default values instead of "0" / "0:00" to avoid ugly "00:000" text on tracks w/o any details

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/CloudTrackItem.jsx
> +                                {points && ` · ${points}`}
Please use better validation for real values, eg dist > 0, points > 0, etc (think about time :-)

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/CloudTrackItem.jsx
> +                    </ClickAwayListener>
ClickAwayListener(s) should have more complicated onClickAway listener to work with "click-out" correctly (see PointContextMenu). Please fix and recheck all other ClickAwayListener(s) which were added recently

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/GpxCollection.jsx
> +import React, { useState } from 'react';
Did you really use React (default import) or just { useState } could be enough?

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/TracksMenu.jsx
> +                            title={'You don’t have track files'}
You don’t have any track files.

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/TracksMenu.jsx
> +                            text={'You can import, create or record track files using OsmAnd App.'}
Just text proposal:

You can sync your tracks with OsmAnd Cloud or use the Create/Import buttons.

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/TracksMenu.jsx
> +                <ClickAwayListener onClickAway={() => setOpenSort(false)}>
Please check earlier onClickAway comment.

2023-11-02 18:58 UTC, RZR-UA commented on map/src/menu/tracks/actions/SortActions.jsx
> +    },
Seems, you've missed the reversed Sort by time (oldest first) method.

2023-11-03 15:31 UTC, RZR-UA approved these changes
well done

2023-11-05 18:31 UTC, RZR-UA requested changes

2023-11-05 18:31 UTC, RZR-UA commented on map/src/infoblock/components/favorite/DeleteFavoriteDialog.jsx
> +        console.log(true);
drop log please

2023-11-06 08:37 UTC, RZR-UA approved these changes

2023-11-06 15:18 UTC, merged