upload track to cloud
osmandapp/web pull request #273
Opened 2023-11-08 15:38 UTC by alisa911

2023-11-08 16:05 UTC, RZR-UA approved these changes

2023-11-08 16:56 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2204

2023-11-09 16:26 UTC, RZR-UA requested changes

2023-11-09 16:26 UTC, RZR-UA commented on map/src/manager/track/TracksManager.js
> +    return foundFolder ? foundFolder.files.find((f) => TracksManager.prepareName(f.name) === name) : false;
1) maybe better name would be folderHasTrack() or isTrackExists()
2) as this is boolean function, better to use "some()" not "find()"
3) please replace find->some in the parent (for local tracks)

2023-11-09 16:26 UTC, RZR-UA commented on map/src/menu/tracks/TrackGroupFolder.jsx
> +            let found = findGroupByName(ctx.tracksGroups, group.fullName, 'fullName');
What is the `'fullName'` in parameters?

2023-11-13 18:00 UTC, RZR-UA commented on map/src/manager/track/SaveTrackManager.js
> +async function refreshGlobalFiles(ctx, params) {
Slightly unclear what are `params` and why only 1 of of params is used. Better to rename params to smth such as `currentFile` or `currentFileName` and additionally change caller's `params` to `params?.name`.

2023-11-13 18:02 UTC, RZR-UA commented on map/src/manager/track/SaveTrackManager.js
> +    const oMyBlob = new Blob([convertedZipped], { type: 'gpx' });
Is it really required to use empty gzip file here? Is the upload-file API requires this?

2023-11-13 18:28 UTC, RZR-UA commented on map/src/menu/tracks/actions/TracksHeader.jsx
> +                setFolderNameError('Folder with same name already exist!');
Folder already exists.

2023-11-13 18:30 UTC, RZR-UA commented on map/src/menu/tracks/actions/TracksHeader.jsx
> +                setFolderNameError('Empty folder name!');
Empty folder name.

2023-11-13 18:34 UTC, RZR-UA commented on map/src/menu/tracks/actions/TracksHeader.jsx
> +    }
Doesn't work in top-level folder.

2023-11-13 18:36 UTC, RZR-UA commented on map/src/menu/tracks/actions/TracksHeader.jsx
> +                    <TextField
1) please run `addFolder()` by Enter key with onKeyPress handler

2) please use `label` or remove unused empty space on the top of the input field

2023-11-14 11:36 UTC, RZR-UA approved these changes

2023-11-16 12:57 UTC, RZR-UA approved these changes

2023-11-16 19:58 UTC, RZR-UA approved these changes

2023-11-17 09:50 UTC, merged