Fav redesign
osmandapp/web pull request #283
Opened 2023-11-28 13:48 UTC by alisa911

2023-11-28 13:48 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2293

2023-11-28 13:49 UTC, RZR-UA approved these changes

2023-12-04 18:04 UTC, RZR-UA commented on map/src/menu/favorite/FavoriteGroupFolder.jsx
> +                return [];
What this `return []` does?

2023-12-05 10:01 UTC, alisa911 commented on map/src/manager/FavoritesManager.js
> +export const DEFAULT_FAV_GROUP_NAME = 'favorites';
favorites

2023-12-05 13:10 UTC, RZR-UA approved these changes

2023-12-05 13:38 UTC, RZR-UA approved these changes

2023-12-05 16:15 UTC, RZR-UA approved these changes

2023-12-08 09:59 UTC, RZR-UA requested changes

2023-12-08 09:59 UTC, RZR-UA commented on map/src/manager/FavoritesManager.js
> +    console.log(newName);
drop the log

2023-12-08 15:04 UTC, RZR-UA approved these changes

2023-12-11 14:58 UTC, RZR-UA requested changes

2023-12-11 14:58 UTC, RZR-UA commented on tests/selenium/src/tests/71-import-delete-favorite-group.mjs
> +        await waitBy(By.id(`se-empty-page`));
` to ' please

2023-12-11 14:58 UTC, RZR-UA commented on tests/selenium/src/util.mjs
> +}
Please change ` to ' everywhere you don't need ${}

2023-12-11 15:01 UTC, RZR-UA requested changes

2023-12-11 15:01 UTC, RZR-UA commented on tests/selenium/src/tests/73-edit-favorite.mjs
> +    await matchTextBy(By.id('se-fav-item-address'), `${suffix}`);
`${suffix}` -> suffix

2023-12-11 15:04 UTC, RZR-UA requested changes

2023-12-11 15:04 UTC, RZR-UA commented on map/src/dialogs/favorites/DeleteFavoriteDialog.jsx
> +                <Button id="se-delete-fav-dialog-submit" onClick={() => deleteWpt()}>
When you don't need any params for event handler, please contract the call:

`onClick={() => deleteWpt()}` -> onClick={deleteWpt}

The same as you've already done at line 96 for onClose.

2023-12-11 15:04 UTC, RZR-UA commented on tests/selenium/src/tests/74-delete-favorite.mjs
> +    await deleteFavGroup(`${shortFavGroupName}`);
-> shortFavGroupName

2023-12-11 15:04 UTC, RZR-UA commented on tests/selenium/src/tests/74-delete-favorite.mjs
> +    await waitBy(By.id(`se-empty-page`));
Please stop using `` instead of ''

2023-12-11 16:54 UTC, merged