show all favorites markers after reload page
osmandapp/web pull request #296
Opened 2023-12-18 18:03 UTC by alisa911

2023-12-18 18:06 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2328

2023-12-20 09:22 UTC, RZR-UA requested changes

2023-12-20 09:22 UTC, RZR-UA commented on map/src/manager/FavoritesManager.js
> +}
Please use { named parameters } when number of parameters is more than 4.

updateGroupAfterChange
updateSelectedFile

2023-12-20 09:22 UTC, RZR-UA commented on map/src/manager/FavoritesManager.js
> +    return `${g.name}/${g.updatetimems}`;
return g.name + '/' + g.updatetimems;

2023-12-20 09:22 UTC, RZR-UA commented on map/src/manager/track/TracksManager.js
> +        }
Please add comment how these raw.push sets are used. How they depend on creationTime and why f?.hiddenupdatetimems is used distinctly?

2023-12-20 09:22 UTC, RZR-UA commented on map/src/menu/actions/FavoriteGroupActions.jsx
> +                changeHidden: true,
You can use shorter form instead of `var: var`:

ctx,
result,
var1: xxx

2023-12-20 09:22 UTC, RZR-UA commented on map/src/util/GzipBase64.mjs
> +    }
Please add default return value: null or {} (as you wish depends on how you use the result)

2023-12-20 09:28 UTC, RZR-UA requested changes

2023-12-20 09:28 UTC, RZR-UA commented on map/src/map/layers/FavoriteLayer.js
> +    }, [ctx.loginUser]);
Please do cleanup for Favorites layer only. Do not remove tracks/navigation/weather/etc

2023-12-20 11:52 UTC, RZR-UA approved these changes

2023-12-20 15:12 UTC, RZR-UA requested changes

2023-12-20 15:12 UTC, RZR-UA commented on map/src/manager/FavoritesManager.js
> +            hiddenChanged: hiddenChanged,
hiddenWasChanged

2023-12-20 18:59 UTC, RZR-UA commented on map/src/infoblock/components/favorite/FavoriteHelper.js
> +            );
>4, please change to named parameters

2023-12-20 18:59 UTC, RZR-UA commented on map/src/menu/favorite/FavoritesMenu.jsx
> +                : null;
Almost unreadable code `... ? : ? : ...`

Please avoid using nested ternaries or try experimental prettier feature for better formatting:

https://prettier.io/blog/2023/11/13/curious-ternaries.html

https://www.sonarsource.com/blog/stop-nesting-ternaries-javascript/

2023-12-20 19:02 UTC, RZR-UA commented on map/src/manager/track/TracksManager.js
> +            raw.push(f?.clienttimems);
If it is possible that clienttimems is not defined (for example, old non-re-uploaded files maybe), please add condition like this: 

`raw.push(f?.clienttimems ?? f?.updatetimems);`

2023-12-21 18:53 UTC, RZR-UA commented on map/src/menu/actions/SortActions.jsx
> +export function sort({ method, setSortFiles, setSortGroups, markers, files, groups, favoriteGroup }) {
Please rename function name `sort()` to something more detailed (to avoid confusing with standard JS .sort() calls).

doSort, sortFilesGroups, etc

2023-12-22 08:58 UTC, RZR-UA approved these changes

2023-12-22 13:15 UTC, merged