Waypoint / Favorites context menu – Web
osmandapp/web pull request #380
Opened 2024-04-08 15:13 UTC by alisa911

2024-04-08 15:14 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2320

2024-04-18 13:50 UTC, RZR-UA requested changes
Finally, please check and fix tests:

[1/2] FAILED 73-edit-favorite.mjs (63.95s) Waiting waitBy*[id="se-empty-page"] 

[2/2] FAILED 75-sort-favorites.mjs (79.29s) Waiting waitBy*[id="se-fav-menu-icon-hidden-shops"]

2024-04-18 13:50 UTC, RZR-UA commented on map/src/dialogs/favorites/DeleteWptDialog.jsx
> +                const lng = ctx.selectedWpt.latlng ? ctx.selectedWpt.latlng.lng : ctx.selectedWpt.lon;
Please check latlng.lng or latlng.lon

2024-04-18 13:50 UTC, RZR-UA commented on map/src/dialogs/favorites/EditWptDialog.jsx
> +                lon: wpt.latlon?.lon ?? wpt.lon,
Please check latlng.lng or latlng.lon

2024-04-18 13:50 UTC, RZR-UA commented on map/src/infoblock/components/tabs/WaypointsTab.jsx
> +    }, [index, mobile, ctx, point]);
Is dep on fill `ctx` really needed here?

2024-04-18 13:50 UTC, RZR-UA commented on map/src/infoblock/components/wpt/WptDetails.jsx
> +                                MarkerOptions.getWptIcon(wpt, wpt?.color, wpt?.background, wpt?.icon).options.html
getWptIcon() has 5 parameters but only 4 are used everywhere, so please recheck and possibly remove unused `folder` parameter

2024-04-18 13:50 UTC, RZR-UA commented on map/src/infoblock/components/wpt/WptDetails.jsx
> +                        {wpt.hidden && (
Please clarify what is `hidden` and why "Hidden: yes" appears on all favorites regardless they were uploaded from gpx or were created in OsmAnd, and even they are not hidden on the map currently.

2024-04-18 13:50 UTC, RZR-UA commented on map/src/infoblock/components/wpt/WptDetails.jsx
> +    const WptLoc = ({ wpt, location }) => {
Please avoid showing this section when there is 0 km distance (= the favorite was just centered on the map).

2024-04-18 13:50 UTC, RZR-UA commented on map/src/manager/track/SaveTrackManager.js
> +    const trackData = gpxFile ? gpxFile : ctx.selectedGpxFile?.file ?? ctx.selectedGpxFile;
Ambigous syntax. Please avoid using `ternary` and `??` together.

2024-04-18 13:50 UTC, RZR-UA commented on map/src/manager/track/SaveTrackManager.js
> +async function downloadAfterUpload(ctx, file, trackData) {
Actually, trackData is not fully used, so possibly better to change it to `showOnMap` parameter with default option specified.

2024-04-19 08:08 UTC, RZR-UA approved these changes

2024-04-19 08:17 UTC, RZR-UA approved these changes

2024-04-19 11:34 UTC, merged