Explore – Web
osmandapp/web pull request #391
Opened 2024-04-29 13:24 UTC by alisa911

2024-04-29 13:24 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2516

2024-05-14 17:12 UTC, RZR-UA requested changes
Finally, please replace `http://` with `https://` in WptTagsProvider.js and WptDetails.jsx and verify the result.

2024-05-14 17:12 UTC, RZR-UA commented on map/src/menu/search/PhotoGallery.jsx
> +    };
Could be 1-liner

2024-05-14 17:12 UTC, RZR-UA commented on map/src/menu/search/PhotoGallery.jsx
> +    const filteredPhotos = filterPhotos(photos).slice(0, 100);
Max 100 photos? Please create const.

2024-05-15 07:37 UTC, RZR-UA approved these changes

2024-05-15 07:53 UTC, merged