add different urls
osmandapp/web pull request #406
Opened 2024-05-23 05:25 UTC by alisa911

2024-05-23 05:25 UTC, alisa911 commented
https://github.com/osmandapp/web/issues/374

2024-05-23 06:37 UTC, RZR-UA commented on map/src/frame/components/GlobalFrame.js
> +                navigate(MAIN_URL + location.hash);
Possibly, the good idea is to include pageParams here to avoid "empty-params flickering"?

2024-05-23 07:00 UTC, RZR-UA requested changes
Please pay attention to forgotten direct /map navigation() here:

file:/login/ChangeEmailDialog.jsx:151:47:                                     navigate('/map/' + window.location.search + window.location.hash);
file:/login/DeleteAccountDialog.jsx:64:23:             navigate('/map/' + window.location.search + window.location.hash);

2024-05-23 17:49 UTC, RZR-UA approved these changes

2024-05-24 07:02 UTC, RZR-UA approved these changes

2024-05-24 08:23 UTC, merged

2024-05-24 08:24 UTC, RZR-UA approved these changes