add search menu, fix urls
osmandapp/web pull request #446
Opened 2024-07-29 14:31 UTC by alisa911

2024-07-29 14:31 UTC, alisa911 commented
https://github.com/osmandapp/web/issues/432

2024-08-12 18:13 UTC, RZR-UA requested changes

2024-08-12 18:13 UTC, RZR-UA commented on map/src/menu/search/search/SearchResults.jsx
> +            alert('Please zoom in closer');
UI for this alert?

2024-08-12 18:13 UTC, RZR-UA commented on map/src/map/layers/SearchLayer.js
> +                setZoom(map.getZoom());
map.off() for 'zoomend' ?

2024-08-12 18:13 UTC, RZR-UA commented on map/src/map/layers/SearchLayer.js
> +            map.on('dragend', () => {
map.off() for 'dragend' ?

2024-08-12 18:13 UTC, RZR-UA commented on map/src/map/layers/SearchLayer.js
> +            if (selectedCategory) {
else { if { -> else if { ?

2024-08-12 18:13 UTC, RZR-UA commented on map/src/map/layers/SearchLayer.js
> +            map.setView([lat, lon], 17);
Please add const ZOOM_TO_MAP = 17

2024-08-15 08:06 UTC, RZR-UA commented
- [ ] when nothing found and search-poi returns null, the progress spinner never stops

2024-08-15 08:48 UTC, RZR-UA approved these changes

2024-08-16 10:15 UTC, RZR-UA approved these changes

2024-08-19 14:15 UTC, alisa911 commented
https://github.com/osmandapp/web/issues/447

2024-08-20 07:38 UTC, merged