Web - display routes and filter by types / years
osmandapp/web pull request #560
Opened 2024-10-29 13:48 UTC by alisa911

2024-10-29 13:49 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2708

2024-11-14 15:17 UTC, RZR-UA requested changes

2024-11-14 15:17 UTC, RZR-UA commented on map/src/infoblock/components/track/GeneralInfo.jsx
> +        return null;
return file?.metaData?.desc ?? file?.description ?? null;

2024-11-14 15:17 UTC, RZR-UA commented on map/src/map/layers/TravelLayer.js
> +                    weight: 3,
Please add const TRAVEL_GPX_TRACK_WIDTH (the magic used 3x times in this file)

2024-11-14 15:17 UTC, RZR-UA commented on map/src/map/layers/TravelLayer.js
> +    const SELECTED_ROUTE_COLOR = '#f8931d';
ROUTE_ -> TRAVEL_GPX_TRACK_ please

2024-11-14 15:17 UTC, RZR-UA commented on map/src/menu/travel/TravelMenu.jsx
> +        ...Array.from({ length: 20 }, (_, i) => {
please start from 2005 up to current year:

`select min (date) from osm_gpx_data = 2005`

2024-11-14 15:17 UTC, RZR-UA commented on map/src/menu/travel/TravelMenu.jsx
> +                    type: 'osmand',
osmand is not a kind of activity anymore

possibly we should add `nospeed` instead of

2024-11-14 15:17 UTC, RZR-UA commented on map/src/setupProxy.js
> +        osmgpx = testProxy;
let's add // TODO swith to mainProxy later

2024-11-15 08:28 UTC, RZR-UA approved these changes

2024-11-15 08:29 UTC, merged